### ISSUE TITLE
I got this error when i try to import flutter_bloc.dar

### ISSUE THREAD

**Issue by TS-RM** [vijayinyoutube/flutter_bloc_cubit_public#3]
I can't understand why i get this error i am so confused !!

import 'package:counter_app/cubit/counter_cubit.dart';
import 'package:flutter/material.dart';
// ! Error
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Colors.grey,
      body: SafeArea(child: ContentPage()),
    );
  }
}

class ContentPage extends StatelessWidget {
  const ContentPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => CounterCubit(),
      child: Center(
        child: Container(
          child: const Text("Home Page"),
        ),
      ),
    );
  }
}

<img width="1329" alt="Screen Shot" src="https://user-images.githubusercontent.com/110350709/187078969-21a9db78-2681-4959-883d-31c39bb1115c.png">

**Comment by vijayinyoutube** [comment]
@TS-RM   did you use the reserved works like `flutter_bloc` , `bloc` any where in the project or as the project name?
